# HYPRIDLE CONFIGURATION

general {
    # Avoid starting multiple hyprlock instances
    lock_cmd = pidof hyprlock || hyprlock
    
    # Ensure the screen is locked before the laptop goes to sleep
    before_sleep_cmd = loginctl lock-session
    
    # Force the screen to turn back on when you wake up the laptop
    after_sleep_cmd = hyprctl dispatch dpms on
}


# LOCK SCREEN
listener {
    timeout = 300 # 5 minutes
    # Trigger the lock command defined in the general block
    on-timeout = loginctl lock-session
}

# KEYBOARD BACKLIGHT
listener {
    timeout = 330 # 5 minutes
    # Save current state and turn off ASUS keyboard backlight
    on-timeout = brightnessctl -sd asus::kbd_backlight set 0
    # Restore keyboard backlight state on wake/activity
    on-resume = brightnessctl -rd asus::kbd_backlight
}

# SCREEN OFF
listener {
    timeout = 330 # 5.5 minutes (30 seconds after locking)
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                            # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r          # screen on when activity is detected after timeout has fired.

}

# 4. SYSTEM SUSPEND
listener {
    timeout = 630 # 5 minutes after screen turns off
    on-timeout = systemctl suspend
}